#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDBJava16Tuesday
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
